Texcel ASPNET En ligne v2/TexcelASPNETbyEddy/Controllers/SEController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;


namespace TexcelASPNETbyEddy.Controllers
{
    public class SEController : Controller
    {
        // GET: SE

        //premier commit franck

        //second commit franck

        BdTexcel_Eddy_FranckEntities bd = new BdTexcel_Eddy_FranckEntities();
        public ActionResult Index()
        {
            return View(bd.tblSEs.ToList());
        }

        // GET: tblSE/Details/5
        public ActionResult Details(int id = 0)
        {
            return View(bd.tblSEs.Find(id));
        }

        // GET: tblSE/Create
        [HttpGet]
        public ActionResult Create()
        {
            //ViewBag.ErreurCreateSE = false;
            return View();
        }

        // POST: tblSE/Create
        [HttpPost]
        public ActionResult Create(tblSE SE)
        {
            try
            {
                // TODO: Add insert logic here
                if (ModelState.IsValid)
                {
                    if(existenceDuSE(SE) == true)
                    {
                        ViewBag.ErreurSE = true;
                        ViewBag.Message = " Ce système d'exploitation existe déja!!! ";

                        return View(SE);
                    }
                    else
                    {
                        SE.tagSE = SE.nomSE + SE.editionSE + SE.versionSE;
                        bd.tblSEs.Add(SE);
                        bd.SaveChanges();
                        return RedirectToAction("Index");
                    }
                   
                }

                return View(SE);
            }
            catch
            {
                return View(SE);
            }
        }

        // GET: tblSE/Edit/5
        public ActionResult Edit(int id=0)
        {
            return View(bd.tblSEs.Find(id));
        }

        // POST: tblSE/Edit/5
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Edit(tblSE SE)
        {
            
                // TODO: Add update logic here

                if (ModelState.IsValid)
                {
                    if (existenceDuSE(SE) == true)
                    {
                        ViewBag.ErreurSE = true;
                        ViewBag.Message = " Ce système d'exploitation existe déja!!! ";

                        return View(SE);
                    }
                    else
                    {
                        //SE.tagSE = SE.nomSE + SE.editionSE + SE.versionSE;
                        
                        bd.Entry(SE).State = EntityState.Modified;

                        bd.SaveChanges();

                        return RedirectToAction("Index");
                    }

                }

                return View(SE);
            /*}
            catch
            {
                return View(SE);
            }*/
        }

        // GET: tblSE/Delete/5
        public ActionResult Delete(int id)
        {
            return View(bd.tblSEs.Find(id));
        }

        // POST: tblSE/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmation(int id)
        {
            tblSE SE = bd.tblSEs.Find(id);

            try
            {
                // TODO: Add delete logic here
                

                if (nombrePlateformeSE(SE) != 0)
                {
                    ViewBag.ErreurSE = true;
                    ViewBag.Message = " Le système d'exploitation est lié a une ou plusieurs plateformes!!! ";

                    return View(SE);
                }
                else
                {
                    bd.tblSEs.Remove(SE);

                    bd.SaveChanges();

                    return RedirectToAction("Index");
                }

            }
            catch
            {
                return View(SE);
            }

        }

        private bool existenceDuSE(tblSE SE)
        {
            List<tblSE> listeDesSE = this.listeDesSE();
            bool existeDansLaBD = false;

            foreach (tblSE se in listeDesSE)
            {
                if (se.nomSE == SE.nomSE && se.editionSE == SE.editionSE && se.versionSE == SE.versionSE)
                {
                    existeDansLaBD = true;
                    break;
                }
            }

            return existeDansLaBD;
        }

        private int nombrePlateformeSE(tblSE SE)
        {
            int nbrePlateformeSE = 0;
            var requeteNbrePlateformeSE = from se in bd.tblSEs
                                          where se.codeSE == SE.codeSE
                                          select se.tblPlateformes.Count();

            foreach (var nombre in requeteNbrePlateformeSE)
            {
                nbrePlateformeSE = nombre;
            }

            return nbrePlateformeSE;
        } 

        private List<tblSE> listeDesSE()
        {
           
            List<tblSE> listeDesSE = new List<tblSE>();

            var query = from se in bd.tblSEs
                        orderby se.codeSE
                        select se;

            foreach (var se in query)
            {
                tblSE SE = new tblSE();
                SE.codeSE = se.codeSE;
                SE.nomSE = se.nomSE;
                SE.editionSE = se.editionSE;
                SE.versionSE = se.versionSE;

                listeDesSE.Add(SE);
            }

            return listeDesSE;
        }

    }
}

Texcel ASPNET En ligne v2/TexcelASPNETbyEddy/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mon application ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <img src="~/Content/images/texcel.png" alt="Texcel" width="70" />

                <!--@Html.ActionLink("TEXCEL", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })-->
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Accueil", "Index", "Home")</li>
                    <li>@Html.ActionLink("Jeux", "Index", "SE")</li>
                    <li>@Html.ActionLink("Plateformes", "Index", "SE")</li>
                    <li>@Html.ActionLink("Systèmes d'exploitation", "Index", "SE")</li>
                    <li>@Html.ActionLink("À propos de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - TEXCEL - Eddy & Franck </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>